<!DOCTYPE html>
<html lang="en">
<head>
    <title>My Account</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="<?php echo $path;?>resources/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <script src="<?php echo $path;?>resources/js/jquery.min.js"></script>
    <script src="<?php echo $path;?>resources/bootstrap/js/bootstrap.min.js"></script>

</head>
<body>

<?php include "menubar.php"; ?>

<?php if (!isset($_SESSION["account"])) { ?>
    <div class="container col-md-6">
        <h2>Register</h2>
        <form role="form" method="post" action="./register">
            <div class="form-group">
                <label for="email">Username:</label>
                <input required name="username" type="text" class="form-control" id="email" placeholder="Username">
            </div>
            <div class="form-group">
                <label for="email">Password:</label>
                <input required name="password" type="password" class="form-control" id="email"
                       placeholder="Password"></input>
            </div>
            <div class="form-group">
                <label for="email">E-mail:</label>
                <input required name="email" type="email" class="form-control" id="email"
                       placeholder="E-mail address"></input>
            </div>
            <div class="form-group">
                <label for="email">Delivery Address:</label>
                <textarea required name="address" type="text" class="form-control" id="email"
                          placeholder="Address"></textarea>
            </div>
            <input type="hidden" name="register" value="register">
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>


    <div class="container col-md-6">
        <h2>Login</h2>
        <form role="form" method="post" action="./account/login">
            <div class="form-group">
                <label for="email">Username:</label>
                <input required name="username" type="text" class="form-control" id="email" placeholder="Username">
            </div>
            <div class="form-group">
                <label for="email">Password:</label>
                <input required name="password" type="password" class="form-control" id="email"
                       placeholder="Password"></input>
            </div>
            <input type="hidden" name="login" value="login">
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>
<?php } elseif (!isset($_GET["order"])) { ?>



    <div class="container">
        <div class="jumbotron">
            <h2>Your address</h2>
            <p id="address" contenteditable="true">
                <?php echo $address; ?>
            </p>
            <button class="btn btn-primary" id="updateAddress">
                Update address
            </button>
        </div>
          <?php // echo $_SESSION["account"]; ?>

    </div>

    <div class="container">
        <h2>Your orders</h2>
        <table class="table table-hover">
            <thead>
            <tr>
                <th>Order ID</th>
                <th>Details</th>
            </tr>
            </thead>
            <tbody>
            <?php
                foreach ($something as $obj) {
                    ?>
                    <tr>
                        <td>
                            <?php echo $obj["_id"]['$oid']; ?>
                        </td>
                        <td>
                            <a href="order/<?php echo $obj["_id"]['$oid']; ?>">
                                Order details
                            </a>
                        </td>
                    </tr>
                <?php }
            ?>

            </tbody>
        </table>
    </div>


<?php } ?>


</body>
<script>
    $(document).ready(function () {
        $("#updateAddress").click(function () {
            $.post("address/save",
                {
                    u_address: $('#address').html()

                },
                function (data, status) {
                    console.log(data)
                    var myArray = jQuery.parseJSON(data);
                    alert(myArray.msg);
                });
        });
    });
</script>
</html>

