<!DOCTYPE html>
<html lang="en">
<head>
    <title>My-Commerce Administration</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="<?php echo $path;?>resources/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <script src="<?php echo $path;?>resources/js/jquery.min.js"></script>
    <script src="<?php echo $path;?>resources/bootstrap/js/bootstrap.min.js"></script>

    <style>
        .container {
            margin-top: 20px;
        }

        .image-preview-input {
            position: relative;
            overflow: hidden;
            margin: 0px;
            color: #333;
            background-color: #fff;
            border-color: #ccc;
        }

        .image-preview-input input[type=file] {
            position: absolute;
            top: 0;
            right: 0;
            margin: 0;
            padding: 0;
            font-size: 20px;
            cursor: pointer;
            opacity: 0;
            filter: alpha(opacity=0);
        }

        .image-preview-input-title {
            margin-left: 2px;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="../">My-Commerce</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="../admin">
                        Home
                    </a>
                </li>
                <li class="active">
                    <a href="../admin/manage">
                        Manage products
                    </a>
                </li>
                <?php if (isset($_SESSION["account"])) { ?>
                    <li class="active">
                        <a href="../account">
                            Orders
                        </a>
                    </li>
                <?php } else { ?>
                    <li class="active">
                        <a href="../account">
                            Login
                        </a>
                    </li>
                <?php } ?>
            </ul>
            <ul class="nav navbar-nav navbar-right">

                <?php if (isset($_SESSION["account"])) { ?>
                    <li>
                        <a href="../account/logout">
                            <span class="glyphicon glyphicon-log-in"></span>
                             Logout
                        </a>
                    </li>
                <?php } ?>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <div class="row">
        <h2>Add a product</h2>
        <form id="data">
            <div class="form-group">
                <label for="email">Product name:</label>
                <input required name="title" type="text" class="form-control" id="email" placeholder="Product name">
            </div>
            <div class="form-group">
                <label for="email">Product description:</label>
            <textarea required name="description" type="text" class="form-control" id="email"
                      placeholder="Product description"></textarea>
            </div>
            <div class="form-group">
                <label for="email">Price:</label>
                <input required name="price" type="number" class="form-control" id="email" placeholder="Price">
            </div>


            <div class="col-xs-12 col-md-6 col-sm-8">
                <!-- image-preview-filename input [CUT FROM HERE]-->
                <div class="input-group image-preview">
                    <input type="text" class="form-control image-preview-filename" disabled="disabled">
                    <!-- don't give a name === doesn't send on POST/GET -->
                <span class="input-group-btn">
                    <!-- image-preview-clear button -->
                    <button type="button" class="btn btn-default image-preview-clear" style="display:none;">
                        <span class="glyphicon glyphicon-remove"></span> Clean
                    </button>
                    <!-- image-preview-input -->
                    <div class="btn btn-default image-preview-input">
                        <span class="glyphicon glyphicon-folder-open"></span>
                        <span class="image-preview-input-title">Browse</span>
                        <input type="file" accept="image/png, image/jpeg, image/gif" name="fileToUpload"/>
                        <!-- rename it -->
                    </div>
                </span>
                </div><!-- /input-group image-preview [TO HERE]-->
            </div>
            <button type="submit" class="btn btn-default" id="addProduct">Save product</button>
        </form>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("form#data").submit(function(event){
         
          //disable the default form submission
          event.preventDefault();
         
          //grab all form data  
          var formData = new FormData($(this)[0]);
         
          $.ajax({
            url: 'manage/add',
            type: 'POST',
            data: formData,
            async: false,
            cache: false,
            contentType: false,
            processData: false,
            success: function (data, status) {
                    var myArray = jQuery.parseJSON(data);
                    alert(myArray.msg);
                    if(myArray.status==200)
                        window.location.href = "manage";
                }
          });

          return false;
        });
      });

    $(document).on('click', '#close-preview', function () {
        $('.image-preview').popover('hide');
        // Hover befor close the preview
        $('.image-preview').hover(
            function () {
                $('.image-preview').popover('show');
            },
            function () {
                $('.image-preview').popover('hide');
            }
        );
    });

    $(function () {
        // Create the close button
        var closebtn = $('<button/>', {
            type: "button",
            text: 'x',
            id: 'close-preview',
            style: 'font-size: initial;',
        });
        closebtn.attr("class", "close pull-right");
        // Set the popover default content
        $('.image-preview').popover({
            trigger: 'manual',
            html: true,
            title: "<strong>Preview</strong>" + $(closebtn)[0].outerHTML,
            content: "Image not found",
            placement: 'bottom'
        });
        // Clear event
        $('.image-preview-clear').click(function () {
            $('.image-preview').attr("data-content", "").popover('hide');
            $('.image-preview-filename').val("");
            $('.image-preview-clear').hide();
            $('.image-preview-input input:file').val("");
            $(".image-preview-input-title").text("Browse");
        });
        // Create the preview image
        $(".image-preview-input input:file").change(function () {
            var img = $('<img/>', {
                id: 'dynamic',
                width: 250,
                height: 200
            });
            var file = this.files[0];
            var reader = new FileReader();
            // Set preview image into the popover data-content
            reader.onload = function (e) {
                $(".image-preview-input-title").text("Change");
                $(".image-preview-clear").show();
                $(".image-preview-filename").val(file.name);
                img.attr('src', e.target.result);
                $(".image-preview").attr("data-content", $(img)[0].outerHTML).popover("show");
            }
            reader.readAsDataURL(file);
        });
    });
</script>
</body>
</html>

