<!DOCTYPE html>
<html lang="en">
<head>
    <title>My-Commerce Administration</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="<?php echo $path;?>resources/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <script src="<?php echo $path;?>resources/js/jquery.min.js"></script>
    <script src="<?php echo $path;?>resources/bootstrap/js/bootstrap.min.js"></script>

    <style>
        .container {
            margin-top: 20px;
        }

        .image-preview-input {
            position: relative;
            overflow: hidden;
            margin: 0px;
            color: #333;
            background-color: #fff;
            border-color: #ccc;
        }

        .image-preview-input input[type=file] {
            position: absolute;
            top: 0;
            right: 0;
            margin: 0;
            padding: 0;
            font-size: 20px;
            cursor: pointer;
            opacity: 0;
            filter: alpha(opacity=0);
        }

        .image-preview-input-title {
            margin-left: 2px;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="../index.php">My-Commerce</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="../admin">
                        Home
                    </a>
                </li>
                <li class="active">
                    <a href="../admin/manage">
                        Manage products
                    </a>
                </li>
                <?php if (isset($_SESSION["account"])) { ?>
                    <li class="active">
                        <a href="../account">
                            Orders
                        </a>
                    </li>
                <?php } else { ?>
                    <li class="active">
                        <a href="../account">
                            Login
                        </a>
                    </li>
                <?php } ?>
            </ul>
            <ul class="nav navbar-nav navbar-right">

                <?php if (isset($_SESSION["account"])) { ?>
                    <li>
                        <a href="<?php echo $path;?>account/account/logout">
                            <span class="glyphicon glyphicon-log-in"></span>
                             Logout
                        </a>
                    </li>
                <?php } ?>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <h2>Manage products</h2>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>Order ID</th>
            <th>Title</th>
            <th>Description</th>
            <th>Price</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>

        <?php
            foreach ($something as $obj) {
                $description = $obj->description;

                if (strlen($description) > 20)
                    $description = substr($description, 0, 17) . '...';
                ?>
                <tr>
                    <td><?php echo $obj->_id; ?></td>
                    <td><?php echo $obj->title; ?></td>
                    <td><?php echo $description; ?></td>
                    <td><?php echo $obj->price; ?></td>
                    <td>
                        <a class="btn btn-warning"
                           href="manage/update/<?php echo $obj->_id; ?>">
                           Update
                       </a>
                        <a class="btn btn-danger"
                           href="manage/delete/<?php echo $obj->_id; ?>">
                           Delete
                       </a>
                    </td>
                </tr>
        <?php
            }
        ?>

        </tbody>
    </table>
</div>


    <script>
        $(document).on('click', '#close-preview', function () {
            $('.image-preview').popover('hide');
            // Hover befor close the preview
            $('.image-preview').hover(
                function () {
                    $('.image-preview').popover('show');
                },
                function () {
                    $('.image-preview').popover('hide');
                }
            );
        });

        $(function () {
            // Create the close button
            var closebtn = $('<button/>', {
                type: "button",
                text: 'x',
                id: 'close-preview',
                style: 'font-size: initial;',
            });
            closebtn.attr("class", "close pull-right");
            // Set the popover default content
            $('.image-preview').popover({
                trigger: 'manual',
                html: true,
                title: "<strong>Vista Previa</strong>" + $(closebtn)[0].outerHTML,
                content: "No hay imagen",
                placement: 'bottom'
            });
            // Clear event
            $('.image-preview-clear').click(function () {
                $('.image-preview').attr("data-content", "").popover('hide');
                $('.image-preview-filename').val("");
                $('.image-preview-clear').hide();
                $('.image-preview-input input:file').val("");
                $(".image-preview-input-title").text("Browse");
            });
            // Create the preview image
            $(".image-preview-input input:file").change(function () {
                var img = $('<img/>', {
                    id: 'dynamic',
                    width: 250,
                    height: 200
                });
                var file = this.files[0];
                var reader = new FileReader();
                // Set preview image into the popover data-content
                reader.onload = function (e) {
                    $(".image-preview-input-title").text("Change");
                    $(".image-preview-clear").show();
                    $(".image-preview-filename").val(file.name);
                    img.attr('src', e.target.result);
                    $(".image-preview").attr("data-content", $(img)[0].outerHTML).popover("show");
                }
                reader.readAsDataURL(file);
            });
        });
    </script>
</body>
</html>